### ISSUE TITLE
Option to customize highlighting groups

### ISSUE THREAD

**Issue by KabbAmine** [haya14busa/vim-signjk-motion#1]
Thanks for your nice plugin :+1:

Currently the only way to define different colors for `SignjkTarget` and `SignjkTarget2` groups is in an _after_ file (Inconvenient of setting hi groups in an _autoload_ file).

So, can we have an option for linking different groups to `SignjkTarget` and `SignjkTarget2`?
e.g.

``` vim
let g:signjk#hi = ['Error', 'Search']
```

**Comment by haya14busa** [comment]
Thank you for the report.

I added `default` to highlight definition, so your defined highlight for SignjkTarget or SignjkTarget2 won't be overwritten now.

**Comment by KabbAmine** [comment]
Works great, thanks (I wasn't aware of `default` keyword).
