### ISSUE TITLE
Wrong motion when used with closed folds

### ISSUE THREAD

**Issue by KabbAmine** [haya14busa/vim-signjk-motion#2]
Please consider the following example:

``` vim
1. foo bar
2. foo bar

" {{{1
1. foo bar
2. foo bar
" 1}}}

1. foo bar
2. foo bar

" vim:ft=vim:fdm=marker:fmr={{{,}}}:
```
- Close the folds.
- Place cursor in line 2.
- Use `<Plug>(signjk-j)` and choose a line after the closed fold.

The cursor will move to the last line.
Note that the same issue occurs when proceeding in a reversed way (Try to move to first lines from after the closed fold).

**Comment by haya14busa** [comment]
Thank you for the report! I fixed it.

**Comment by KabbAmine** [comment]
That was quick :open_mouth:
