### ISSUE TITLE
Symbol at top of sign column

### ISSUE THREAD

**Issue by SevereOverfl0w** [haya14busa/vim-signjk-motion#3]
https://i.imgur.com/eWELKwd.png

This is caused by the dummysign, disabling it via 

``` vimscript
let g:signjk#dummysign = 0
```

gets rid of it.

~~Is there a reason the dummysign is there?~~ ah, it's to keep the signcolumn open at all times.

I'm using neovim, so it may be a bug introduced from them, although the name suggests it might be a workaround for a vim bug.

**Comment by SevereOverfl0w** [comment]
The symbol of dummysign is visible under my font configuration.

I have observed you can define a sign _without_ `text=[]` and it will still be invisible, is there a reason there needs to be an invisible symbol instead?

**Comment by haya14busa** [comment]
I didn't notice that `text` can be omitted. Thanks! I fixed it.
